### ISSUE TITLE
data.button_last_state

### ISSUE THREAD

**Issue by johro897** [Sian-Lee-SA/Home-Assistant-Switch-Manager#116]
I am trying to use data.button_last_state in order to repeat an action when a button is hold.
I can see in the debug that when a button is released:
data.button_last_state[0].action : {
    "action": 1,
    "title": "hold",
    "timestamp": 1680176897.8251488
}
![image](https://user-images.githubusercontent.com/31991203/228840799-47b25095-0f62-46ac-9fcf-4c7392851d05.png)

I have then tried to call this in the button actions without any success.
```
repeat:
  until:
    - condition: template
      value_template: "{{ data.button_last_state[0].title == 'hold' }}"
  sequence:
    - service: light.turn_on
      data:
        brightness_step_pct: 10
      target:
        entity_id: light.led_1
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
enabled: true
````

If I understand your manual correct this is hown it should be done, but the loop never ends. Instead the loop goes on until i de-activate the code.

**Comment by Sian-Lee-SA** [comment]
Does the device send a released state?

**Comment by Sian-Lee-SA** [comment]
I'm confused, neither of them are "hold (released)".... Does the effect stop when you press the button again by a single press?

**Comment by johro897** [comment]
last_state will not show "hold (released)" until I press the button again
Picture above:
First is Pressing button "hold" action=1, second is releasing button "hold (release) action=2

But even though the last_state after i released the button is action=1 title="hold" the data.button_last_state[0] doesnt seem to be usable in the button action

**Comment by johro897** [comment]
> Think about it logically... You are looping something where the state equals hold... That state doesn't change because I can't see anywhere where the state changes after hold. Either your blueprint isn't configured correctly or your device doesn't support a released state.

The logic would be that when i release, which is in the second part of the picture, the last_state would be previous state which is hold and that is correct, but the switchmanager doesnt seem to read the variable data.button_last_state since the break of the loop never happens

**Comment by johro897** [comment]
The button_last_state changes to hold when i release (action=2)
![image](https://user-images.githubusercontent.com/31991203/228884056-0e63686c-acd5-46b9-90d3-18d956b28ba5.png)

**Comment by johro897** [comment]
I think the logic is correct.
From what I get the variable doesnt seem to be exposed when you set the actions of the button. (sorry for Swedish in the pic)

![image](https://user-images.githubusercontent.com/31991203/228885059-1ed388d7-8b17-48cb-9225-145338ce3679.png)

**Comment by Sian-Lee-SA** [comment]
try with {{ data.button_last_state[0].title = 'press' }}

**Comment by Sian-Lee-SA** [comment]
Technically button_last_state is meant to be used for other buttons to reference and not for self referencing... It's just a helper variable. That's how the examples in the readme works.

**Comment by johro897** [comment]
ok, FYI how I made it work.
Added variable
`released:0`

on hold(released:
```
- service: switch_manager.set_variables
  data:
    switch_id: 1
    variables:
      released: 1
```
on Hold
```
- repeat:
    until:
      - condition: template
        value_template: "{{ data.variables.released == 1 }}"
    sequence:
      - service: light.turn_on
        data:
          brightness_step_pct: -10
        target:
          entity_id: light.led_1
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 500
  enabled: true
- service: switch_manager.set_variables
  data:
    switch_id: 1
    variables:
      released: 0
```
