### ISSUE TITLE
Zigbee2MQTT / Ikea On/Off Remote E1743 - 2 actions respond to 1 command

### ISSUE THREAD

**Issue by jhhbe** [Sian-Lee-SA/Home-Assistant-Switch-Manager#117]
Issue is that hold (released) has the same MQTT action payload for release after on or off. So it will trigger both for on - hold (released) and off - hold (released) regardless what was released. Probably less confusing in code - see brightness_stop:

```
buttons:
  - x: 192
    y: 149
    width: 93
    actions:
      - title: press
        conditions:
          - key: payload
            value: "on"
      - title: hold
        conditions:
          - key: payload
            value: brightness_move_up
      - title: hold (released)
        conditions:
          - key: payload
            value: brightness_stop
  - x: 192
    y: 372
    width: 93
    actions:
      - title: press
        conditions:
          - key: payload
            value: "off"
      - title: hold
        conditions:
          - key: payload
            value: brightness_move_down
      - title: hold (released)
        conditions:
          - key: payload
            value: brightness_stop
```

Not sure what is the most elegant way to solve this? Zigbee2MQTT - Ikea SYMFONISK Sound remote (E1744) has a similar problem: it does not know if rotate (stop) is stopping after clockwise or counterclockwise rotation. On that one the approach is a single event ignoring sense of rotation, so it triggers only once independent of rotation sense.
An option might be to have a helper variable remember previous action but that (almost) pushes you back into automations while Switch Manager has been a great way to significantly reduce the number of automations I had.

Finally, this is not that wrong, but it may be confusing to users - after all the button is sending the same payload for 2 different actions. Issue is that now it is responding twice.
