### ISSUE TITLE
mqtt, won't work when json value in []array

### ISSUE THREAD

**Issue by zylxpl** [Sian-Lee-SA/Home-Assistant-Switch-Manager#129]
Hello, trying to create blueprint for Shelly 2 PM connected via mqtt. However, values i need to use are in the [...] array in json payload, and it is not working. Sample mqtt payload:

```
{
    "src": "shellyplus2pm-b8d61a89b8c8",
    "dst": "shellyplus2pm-b8d61a89b8c8/events",
    "method": "NotifyEvent",
    "params": {
        "ts": 1684890281.22,
        "events": [
            {
                "component": "input:1",
                "id": 1,
                "event": "single_push",
                "ts": 1684890281.22
            }
        ]
    }
}
```

and my blueprint:
```
name: Shelly Plus 2pm mqtt
service: Shelly
event_type: mqtt
mqtt_topic_format: +/events/rpc
buttons:
  - x: 110
    y: 123
    width: 66
    height: 66
    conditions:
      - key: params.events[0].id
        value: 0
    actions:
      - title: tap
        conditions:
          - key: params.events[0].event
            value: single_push
      - title: hold
        conditions:
          - key: params.events[0].event
            value: long_push
```

**Comment by Sian-Lee-SA** [comment]
change array keys to periods instead of []. params.events.0..id

**Comment by zylxpl** [comment]
Thank you, works like a charm. Any interest for it to be push to master (i can also add int, double etc to normal shelly blueprints)? :
```yaml
name: Shelly Plus 2PM MQTT
service: Shelly
event_type: mqtt
mqtt_topic_format: +/events/rpc
buttons:
  - x: 110
    y: 123
    width: 66
    height: 66
    conditions:
      - key: params.events.0.id
        value: 0
    actions:
      - title: init
        conditions:
          - key: params.events.0.event
            value: btn_down
      - title: press
        conditions:
          - key: params.events.0.event
            value: single_push
      - title: press 2x
        conditions:
          - key: params.events.0.event
            value: double_push
      - title: press 3x
        conditions:
          - key: params.events.0.event
            value: triple_push
      - title: hold
        conditions:
          - key: params.events.0.event
            value: long_push
      - title: hold (released)
        conditions:
          - key: params.events.0.event
            value: btn_up

  - x: 110
    y: 241
    width: 66
    height: 66
    conditions:
      - key: params.events.0.id
        value: 1
    actions:
      - title: init
        conditions:
          - key: params.events.0.event
            value: btn_down
      - title: press
        conditions:
          - key: params.events.0.event
            value: single_push
      - title: press 2x
        conditions:
          - key: params.events.0.event
            value: double_push
      - title: press 3x
        conditions:
          - key: params.events.0.event
            value: triple_push
      - title: hold
        conditions:
          - key: params.events.0.event
            value: long_push
      - title: hold (released)
        conditions:
          - key: params.events.0.event
            value: btn_up
```

**Comment by Sian-Lee-SA** [comment]
Cool glad it worked out. Feel free to PR if you wish. Adding an init to the other shelly's sounds fine although it will cause a misconfig for users who are already using that blueprint so it's not always ideal to update a blueprint once it's published from a previous release.

**Comment by spacerunner5** [comment]
I found this thread and it helped me getting a **Shelly Plus i4 Gen3** working over MQTT. 

Reason: As soon as you enable **Button Mode** in the Shelly, the device sends a RPC / JSON payload to MQTT. That does not happen when using "switch" mode. Disabling RPC in the Shelly MQTT settings completely disables getting Button messages to MQTT.

Just in case someone else has this kind of problem, here is the blueprint for the Shelly Plus i4 Gen3:


```yaml
# Shelly Plus i4 Gen3 MQTT RPC 
# Switch Manager Blueprint for Button Mode
#
# inspired by https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/129
#
# Using Shelly Mode "Button" on the Shelly 4 Plus, the device  will not send
# raw mqtt messages to the broker, but instead use RPC formated messages.
#
# Image mappings for image shelly-wall-switch4.png

name: Shelly Plus i4 MQTT
service: Shelly MQTT RPC
event_type: mqtt
mqtt_topic_format: +/events/rpc
buttons:
  - x: 40
    y: 40
    width: 169
    height: 169
    conditions:
      - key: params.events.0.id
        value: 0
    actions:
      - title: init
        conditions:
          - key: params.events.0.event
            value: btn_down
      - title: press
        conditions:
          - key: params.events.0.event
            value: single_push
      - title: press 2x
        conditions:
          - key: params.events.0.event
            value: double_push
      - title: press 3x
        conditions:
          - key: params.events.0.event
            value: triple_push
      - title: hold
        conditions:
          - key: params.events.0.event
            value: long_push
      - title: hold (released)
        conditions:
          - key: params.events.0.event
            value: btn_up
  - x: 219
    y: 40
    width: 169
    height: 169
    conditions:
      - key: params.events.0.id
        value: 1
    actions:
      - title: init
        conditions:
          - key: params.events.0.event
            value: btn_down
      - title: press
        conditions:
          - key: params.events.0.event
            value: single_push
      - title: press 2x
        conditions:
          - key: params.events.0.event
            value: double_push
      - title: press 3x
        conditions:
          - key: params.events.0.event
            value: triple_push
      - title: hold
        conditions:
          - key: params.events.0.event
            value: long_push
      - title: hold (released)
        conditions:
          - key: params.events.0.event
            value: btn_up
  - x: 40
    y: 219
    width: 169
    height: 169
    conditions:
      - key: params.events.0.id
        value: 2
    actions:
      - title: init
        conditions:
          - key: params.events.0.event
            value: btn_down
      - title: press
        conditions:
          - key: params.events.0.event
            value: single_push
      - title: press 2x
        conditions:
          - key: params.events.0.event
            value: double_push
      - title: press 3x
        conditions:
          - key: params.events.0.event
            value: triple_push
      - title: hold
        conditions:
          - key: params.events.0.event
            value: long_push
      - title: hold (released)
        conditions:
          - key: params.events.0.event
            value: btn_up
  - x: 219
    y: 219
    width: 169
    height: 169
    conditions:
      - key: params.events.0.id
        value: 3
    actions:
      - title: init
        conditions:
          - key: params.events.0.event
            value: btn_down
      - title: press
        conditions:
          - key: params.events.0.event
            value: single_push
      - title: press 2x
        conditions:
          - key: params.events.0.event
            value: double_push
      - title: press 3x
        conditions:
          - key: params.events.0.event
            value: triple_push
      - title: hold
        conditions:
          - key: params.events.0.event
            value: long_push
      - title: hold (released)
        conditions:
          - key: params.events.0.event
            value: btn_up

```
