### ISSUE TITLE
Shelly Gen 1, mqtt can't setup state topic

### ISSUE THREAD

**Issue by zylxpl** [Sian-Lee-SA/Home-Assistant-Switch-Manager#133]
Trying to create blueprint for mqtt switch that publish physical state under topic:
`shellies/+/input/0`  and `shellies/+/input/1` as payload 0 or 1. Verified multiple times that the topic name is correct:
![image](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/13242378/3149e1d8-3d19-46b1-864a-cee284856010).
However , for some reason Switch Manager is not recognizing this topic no matter what i try. What is even more strange, when i set up mqtt topic for a switch with #, fe `shellies/shellyswitch25-xxxxxxxxxxxx/#`  i can see messages in debug consoles from all other topics associated with this switch (/relay, /input_event, /temperature etc) but not for `input/0` or `input/1` .

MQTT documentation for this switch: https://shelly-api-docs.shelly.cloud/gen1/#shelly2-5-mqtt

```yaml
name: Shelly 2.5 MQTT
service: Shelly
event_type: mqtt
mqtt_topic_format: shellies/+/input/#
buttons:
  - x: 110
    y: 123
    width: 66
    height: 66
    conditions: "{{ data.topic_basename == '0' }}"
    actions:
      - title: init
        conditions:
          - key: payload
            value: "1"
      - title: hold (released)
        conditions:
          - key: payload
            value: "0"

```

**Comment by Sian-Lee-SA** [comment]
Firstly, conditions: "{{ data.topic_basename == '0' }}" is redundant and does not need to be there.

Second, the payload are integers, try removing the qoutes from the value

**Comment by zylxpl** [comment]
This is only part of the code, as this device have two switches, second one is using `conditions: "{{ data.topic_basename == '0' }}"`. Anyway, i try to set up it with only 1 switch, setting exact topic name and removing conditions, no difference.  Also tried without quotes, same result. 
What is strange, when i set topic like `shellies/shellyswitch25-xxxxxxxxxxxx/#` in mqtt tool, i can see messages coming to `/input/0` and `/input/1` topics, but if i set up the same in Switch Manager cant find anything in debug console (but every other topic pops there).

**Comment by zylxpl** [comment]
Yes, i did exactly that, and it was not working. How can i create mqtt dump??
Also, i was experimenting with sub topic setting, but could not understand how it exactly suppose to work. Where do i need to define subtopics?

**Comment by Sian-Lee-SA** [comment]
Easiest way is just get mqtt explorer and just screen shot the topics. I will put the subtopic stuff in and send you an example blueprint once I get it working.

**Comment by zylxpl** [comment]
![image](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/13242378/497f8cae-f7f7-401c-8a68-9173b8216bc1)
Is this enough?
Can use event bus, as my shelly device's are only connected to ha via mqtt (they are in separate locations)

**Comment by Sian-Lee-SA** [comment]
Could you please update Switch Manager to v1.2.1 as I found a bug that would've been causing you the issues.

The following example should get you going.
```yaml
name: Shelly 2.5 MQTT
service: Shelly
event_type: mqtt
mqtt_topic_format: shellies/+/input
mqtt_sub_topics: true
buttons:
  - conditions: 
      - key: topic_basename
        value: "1"
    actions:
      - title: init
        conditions:
          - key: payload
            value: 1
      - title: hold (released)
        conditions:
          - key: payload
            value: 0
```
 Take note of `mqtt_sub_topics: true`. This means that your set topic should be shellies/shellyswitch25-xxxxxxxxxxxx/input and the sub topics from there will automatically be handled by the blueprint.
