### ISSUE TITLE
New device submission ZHA Moes Star Ring 2 gang remote

### ISSUE THREAD

**Issue by gorstj** [Sian-Lee-SA/Home-Assistant-Switch-Manager#182]
Is it possible to submit a new device for consideration of inclusion in the plugin please:

Image:
![zha-moes-star_ring_2g](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/2826513/c5d50bcd-c137-444b-9802-29e3bce0b66d)

zha-moes-star_ring_2g.yaml

```
name: Moes Star Ring Scene 2g
service: ZHA
event_type: zha_event
identifier_key: device_id
buttons:
  - x: 310
    y: 220
    width: 32
    conditions:
      - key: endpoint_id
        value: 1
    actions:
      - title: press
        conditions:
          - key: command
            value: remote_button_short_press
      - title: press 2x
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
  - x: 535
    y: 220
    width: 32
    conditions:
      - key: endpoint_id
        value: 2
    actions:
      - title: press
        conditions:
          - key: command
            value: remote_button_short_press
      - title: press 2x
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
  - x: 310
    y: 635
    width: 32
    conditions:
      - key: endpoint_id
        value: 3
    actions:
      - title: press
        conditions:
          - key: command
            value: remote_button_short_press
      - title: press 2x
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
  - x: 535
    y: 635
    width: 32
    conditions:
      - key: endpoint_id
        value: 4
    actions:
      - title: press
        conditions:
          - key: command
            value: remote_button_short_press
      - title: press 2x
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
```
