### ISSUE TITLE
[New Feature] Sonoff SNZB-01P

### ISSUE THREAD

**Issue by harvindhillon** [Sian-Lee-SA/Home-Assistant-Switch-Manager#209]
Support for the newer ZNZB-01P Sonoff button

**Comment by harvindhillon** [comment]
![zha-sonoff-snzb-01p](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/95908970/c7eb5cd3-aa71-4b91-ba19-56812e4fd4a1)
```
name: Sonoff SNZB 01P
service: ZHA
event_type: zha_event
identifier_key: device_id
buttons:
  - actions:
      - title: press
        conditions:
          - key: command
            value: "toggle"
      - title: press 2x
        conditions:
          - key: command
            value: "on"
      - title: hold
        conditions:
          - key: command
            value: "off"
```
