### ISSUE TITLE
zha intigation

### ISSUE THREAD

**Issue by chrissileinus** [Sian-Lee-SA/Home-Assistant-Switch-Manager#21]
Are there any plan`s to adapt zha or is it possible? Are there examples?

**Comment by Sian-Lee-SA** [comment]
Sure, just follow the blueprint guide and use zha_event as the event type

**Comment by Sian-Lee-SA** [comment]
I also assume the identifier_key would be device_id

**Comment by chrissileinus** [comment]
ah more or less like the z-wave example.

**Comment by Sian-Lee-SA** [comment]
Yes exactly. I don't use ZHA but it uses events for switches and button presses so the concept is the same as the z-wave

**Comment by chrissileinus** [comment]
I will figure it out. and poste the result

**Comment by chrissileinus** [comment]
I adapted the `zigbee2mqtt-tuya-4-button-scene` example an created this.
but it didn`t apears in HA after a restart.

zha-tuya-4-button-scene
```
name: zha Tuya 4 Button Scene
service: zha
event_type: zha_event
identifier_key: device_id
buttons:
  ## Not sure why the buttons are back to front and illogical by their numbers??
  - x: 23
    y: 23
    width: 216
    height: 208
    conditions:
      - key: endpoint_id
        value: 1
    actions:
      - title: tap
        conditions:
          - key: payload
            value: remote_button_short_press
      - title: double tap
        conditions:
          - key: payload
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: payload
            value: remote_button_long_press
  - x: 239
    y: 23
    width: 216
    height: 208
    conditions:
      - key: endpoint_id
        value: 2
    actions:
      - title: tap
        conditions:
          - key: payload
            value: remote_button_short_press
      - title: double tap
        conditions:
          - key: payload
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: payload
            value: remote_button_long_press
  - x: 23
    y: 231
    width: 216
    height: 208
    conditions:
      - key: endpoint_id
        value: 3
    actions:
      - title: tap
        conditions:
          - key: payload
            value: remote_button_short_press
      - title: double tap
        conditions:
          - key: payload
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: payload
            value: remote_button_long_press
  - x: 239
    y: 231
    width: 216
    height: 208
    conditions:
      - key: endpoint_id
        value: 4
    actions:
      - title: tap
        conditions:
          - key: payload
            value: remote_button_short_press
      - title: double tap
        conditions:
          - key: payload
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: payload
            value: remote_button_long_press
```

**Comment by Sian-Lee-SA** [comment]
So you made that file @ `{home-assistant-config-dir}/blueprints/switch_manager/philips-hue-dimmer-v2.yaml`? the yaml code looks fine to me. Also check logs incase there was a parse error

**Comment by Sian-Lee-SA** [comment]
you're also doing zha and not zigbee2mqtt so  I would change the filename to zha-tuya-4-button-scene

**Comment by chrissileinus** [comment]
yes the path is correct and the filename is `zha-tuya-4-button-scene.yaml` and notrhing in the logs.

only
```
2022-12-20 16:35:13.770 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration switch_manager which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by Sian-Lee-SA** [comment]
Sorry, I read the first filename you mentioned and didn't see what you changed the filename to... That log warning is normal for any custom integration... To be honest, there shouldn't be a reason why it doesn't show. If using linux I can only suggest checking the file permissions.

**Comment by Sian-Lee-SA** [comment]
I just copied your code and created the yaml file and it shows up for me

**Comment by chrissileinus** [comment]
Maybe a problem with the grouping in the UI?

**Comment by Sian-Lee-SA** [comment]
Can't be, I did exactly what you did and shows up. 
![Screenshot 2022-12-21 032701](https://user-images.githubusercontent.com/11685433/208723009-8463ad66-b0d6-442b-99c9-24a101caa0a5.png)

**Comment by Sian-Lee-SA** [comment]
The only other thing I can ask is if you made sure its a yaml file and that windows hasn't hidden the txt file extension, I generally don't ask this because i assume people should be aware of this but sometimes it's overlooked

**Comment by chrissileinus** [comment]
Yea i found my pithole

**Comment by chrissileinus** [comment]
Sorry for all the hussle

**Comment by Sian-Lee-SA** [comment]
Ahh ok, glad you hunted it down... Also if you havent done so already, just copy the png file to the same name for the image to show... All good

**Comment by chrissileinus** [comment]
yes i done it and now testing

**Comment by Sian-Lee-SA** [comment]
If your config works as shown above then I'd happy to add it to this repo

**Comment by Sian-Lee-SA** [comment]
You'll want to change the actions condition keys from payload to command

**Comment by chrissileinus** [comment]
yes i sah it also

**Comment by chrissileinus** [comment]
It`s working!

```
name: Tuya 4 Button Scene
service: zha
event_type: zha_event
identifier_key: device_id
buttons:
  - x: 23
    y: 23
    width: 216
    height: 208
    conditions:
      - key: endpoint_id
        value: 1
    actions:
      - title: tap
        conditions:
          - key: command
            value: remote_button_short_press
      - title: double tap
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
  - x: 239
    y: 23
    width: 216
    height: 208
    conditions:
      - key: endpoint_id
        value: 2
    actions:
      - title: tap
        conditions:
          - key: command
            value: remote_button_short_press
      - title: double tap
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
  - x: 23
    y: 231
    width: 216
    height: 208
    conditions:
      - key: endpoint_id
        value: 3
    actions:
      - title: tap
        conditions:
          - key: command
            value: remote_button_short_press
      - title: double tap
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
  - x: 239
    y: 231
    width: 216
    height: 208
    conditions:
      - key: endpoint_id
        value: 4
    actions:
      - title: tap
        conditions:
          - key: command
            value: remote_button_short_press
      - title: double tap
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
```
