### ISSUE TITLE
Zigbee2MQTT - Philips Hue Tap Switch Support

### ISSUE THREAD

**Issue by FrankGiesecke** [Sian-Lee-SA/Home-Assistant-Switch-Manager#236]
Please, add Zigbee2MQTT - Philips Hue Tap Switch Support

I've tried to add the Blueprint, but even with restarting my HA instance, it doesn't appear in the list of buttons. Where is my mistake?

/root/config/custom_components/switch_manager/blueprints/zigbee2mqtt-philips-hue-tap.yaml
```yaml
name: Philips Hue Tap Switch
service: Zigbee2MQTT
event_type: mqtt
mqtt_topic_format: zigbee2mqtt/+/action
buttons:
  - actions:
      - title: press
        conditions:
          - key: payload
            value: press_1
  - actions:
      - title: press
        conditions:
          - key: payload
            value: press_2
  - actions:
      - title: press
        conditions:
          - key: payload
            value: press_3
  - actions:
      - title: press
        conditions:
          - key: payload
            value: press_4
```

As image, I copied the original image from the Philips Hue blueprint...
```bash
cp philips-hue-tap.png zigbee2mqtt-philips-hue-tap.png
```
