### ISSUE TITLE
Ikea Strybar brightness_stop_up / brightness_stop_down no more available

### ISSUE THREAD

**Issue by b2un0** [Sian-Lee-SA/Home-Assistant-Switch-Manager#248]
with the latest firmware `2.4.16` for the Ikea E2001/E2002 the are `brightness_stop_up` /and`brightness_stop_down` actions are nor more available

this also documented here:
https://www.zigbee2mqtt.io/devices/E2001_E2002.html

```jsonc
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro Remote/action', payload 'brightness_move_down'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro Remote/action', payload 'brightness_stop'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro Remote/action', payload 'brightness_move_up'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro Remote/action', payload 'brightness_stop'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro Remote/action', payload 'arrow_left_hold'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro Remote/action', payload 'arrow_left_release'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro Remote/action', payload 'arrow_right_hold'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro Remote/action', payload 'arrow_right_release'
```

affected:

https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/blob/f54a72355c45d3fba96f266d62e5be674af8899b/custom_components/switch_manager/blueprints/zigbee2mqtt-ikea-styrbar.yaml#L22

https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/blob/f54a72355c45d3fba96f266d62e5be674af8899b/custom_components/switch_manager/blueprints/zigbee2mqtt-ikea-styrbar.yaml#L54

**Comment by b2un0** [comment]
The Ikea RODRET ([E2201](https://www.zigbee2mqtt.io/devices/E2201.html#ikea-e2201)) with Firmware `1.0.57` is also affected.

```jsonc
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Ikea E2201/action', payload 'off'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Ikea E2201/action', payload 'on'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Ikea E2201/action', payload 'brightness_move_down'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Ikea E2201/action', payload 'brightness_stop'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Ikea E2201/action', payload 'brightness_move_up'
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Ikea E2201/action', payload 'brightness_stop'
````


https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/blob/f54a72355c45d3fba96f266d62e5be674af8899b/custom_components/switch_manager/blueprints/zigbee2mqtt-ikea-e2201.yaml#L21

https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/blob/f54a72355c45d3fba96f266d62e5be674af8899b/custom_components/switch_manager/blueprints/zigbee2mqtt-ikea-e2201.yaml#L37

**Comment by b2un0** [comment]
relates to https://github.com/Koenkk/zigbee2mqtt/discussions/23668

**Comment by b2un0** [comment]
ups, looks like a duplicate to #214

**Comment by Sian-Lee-SA** [comment]
I will update the styrbar as I am the author but someone who owns the RODRET or the author of that blueprint will need to update it. Must say it is a bit annoying when they make these small changes.

**Comment by b2un0** [comment]
exactly the same behavior for `RODRET` / `E2201` :(

**Comment by Sian-Lee-SA** [comment]
Did you change it in `\home-assistant\config\blueprints\switch_manager` path and not the component path?

**Comment by Sian-Lee-SA** [comment]
Also the issue with this recent change (whether it's because of Ikea _*my money is on them_ or Z2M), it will mean that both buttons are always going to execute their actions on released. You will need to add some logic and check if hold for either button was pushed last to differentiate which one to act on.

**Comment by b2un0** [comment]
gnah, thanks. 

i edited the blueprint in the component path -.-

now it works :) 

![image](https://github.com/user-attachments/assets/81bbaf6d-0503-440d-ae24-9828dd3e007c)

**Comment by Sian-Lee-SA** [comment]
Cool, I've pushed the changes so should also be in next release. But again, that's only for Styrbar, will wait for someone to do the Rodret

**Comment by b2un0** [comment]
> Also the issue with this recent change (whether it's because of Ikea _*my money is on them_ or Z2M), it will mean that both buttons are always going to execute their actions on released. You will need to add some logic and check if hold for either button was pushed last to differentiate which one to act on.

yes, i know. i have already a workaround for this.

i created a boolean helper for each ikea remote i have and created a while condition:

hold_up
![image](https://github.com/user-attachments/assets/59611524-8ba7-4028-8605-668936edcbaa)

hold_up AND hold_down released:
![image](https://github.com/user-attachments/assets/252fb7ba-e5ea-4a1f-9bbe-98222b4fb7d3)

**Comment by b2un0** [comment]
PR #250 for Rodret created

**Comment by b2un0** [comment]
and for copy paste:

# hold

```yaml
- data: {}
  target:
    entity_id: input_boolean.buro_remote_state_helper
  service: input_boolean.turn_on
- repeat:
    while:
      - condition: state
        entity_id: input_boolean.buro_remote_state_helper
        state: "on"
    sequence:
      - data:
          brightness_step_pct: 10
        target:
          entity_id: light.buro
        action: light.turn_on
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  enabled: true
```

# hold released

```yaml
- data: {}
  target:
    entity_id: input_boolean.buro_remote_state_helper
  service: input_boolean.turn_off
```
