### ISSUE TITLE
Broken on HA2024.8

### ISSUE THREAD

**Issue by adidoes** [Sian-Lee-SA/Home-Assistant-Switch-Manager#249]
I'm trying this addon for the first time, I'm on HA 2024.8 and saving in the switch editor seems to alter the yaml in a way that breaks it (see screenshots below).

I suspect this is because HA changed the "service" keyword to "action" and maybe they're doing that automatically for the switch editor form too.

**Before save:**
<img width="366" alt="image" src="https://github.com/user-attachments/assets/5ee44ec5-3844-4d7c-a700-1e190dea422a">

YAML:

```yaml
- service: light.toggle
  data: {}
  target:
    entity_id: light.living_room_light
```

**After save:**
<img width="399" alt="image" src="https://github.com/user-attachments/assets/12d76b12-f036-4a14-8a63-56bf11bbbb57">

YAML:

```yaml
- data: {}
  target:
    entity_id: light.living_room_light
  action: light.toggle
```

I tried clearing cache/different browsers and even the mobile app so it doesn't seem to be a cache issue.
