### ISSUE TITLE
[Help] New Blueprints not loaded/shown

### ISSUE THREAD

**Issue by nicknol** [Sian-Lee-SA/Home-Assistant-Switch-Manager#280]
I am trying to create a blueprint and I followed the advices given in the docs, especially regarding naming conventions.

**The first and simple blueprint**
```
name: Lidl Smart Button SSBM A1
service: ZHA
event_type: zha_event
identifier_key: device_id
buttons:
  - actions:
      - title: single press
        conditions:
          - key: command
            value: on
      - title: double press
        conditions:
          - key: command
            value: off
      - title: long
        conditions:
          - key: command
            value: stop
```

**File Locations**
I placed the yaml and the png in
`/config/custom_components/switch_manager/blueprints`

```
/config/custom_components/switch_manager/blueprints/zha-lidl-smartbutton-ssbm-a1.png
/config/custom_components/switch_manager/blueprints/zha-lidl-smartbutton-ssbm-a1.yaml

```

**Activation(?)**
I called
`switch_manager.reload`
via developer tools to activate/see it in switch manager.
I even restarted HA, but the blueprint is still not shown in the UI

**_The issue_**
But: my blueprint is not showing up - what could I have done wrong?
