### ISSUE TITLE
[Help] Action generated by UI not working

### ISSUE THREAD

**Issue by nicknol** [Sian-Lee-SA/Home-Assistant-Switch-Manager#281]
I am trying the most simple action for the single press and I get an error in the developer console.

```
- action: switch.toggle
  metadata: {}
  data: {}
  target:
    entity_id: switch.switch_3lt_socket
```
The code snippet was created by the UI, no manual intervention.
![grafik](https://github.com/user-attachments/assets/d9993503-abce-4457-95b9-d7ca75e5e474)

and I get in Developer Console:

`Object { code: "invalid_format", message: "extra keys not allowed @ data['action']. Got {'action': 'switch.toggle', 'metadata': {}, 'data': {}, 'target': {'entity_id': 'switch.switch_3lt_socket'}}" }`
