### ISSUE TITLE
How to setup increase/decrease brightness hold switch

### ISSUE THREAD

**Issue by richardbabangida** [Sian-Lee-SA/Home-Assistant-Switch-Manager#289]
I created the following automation, but I'm unable to add it to the switch manager. It seems that I don't have all the options available in the switch manager. Is there another way to implement a "brightness up" action when holding a button?

```
alias: Ikea remote logia
description: ""
triggers:
  - domain: mqtt
    device_id: 8856236680a74e205aca11774abd3195
    type: action
    subtype: brightness_move_up
    trigger: device
    id: dim-up
  - domain: mqtt
    device_id: 8856236680a74e205aca11774abd3195
    type: action
    subtype: brightness_move_down
    trigger: device
    id: dim-down
  - domain: mqtt
    device_id: 8856236680a74e205aca11774abd3195
    type: action
    subtype: brightness_stop
    trigger: device
    id: dim-released
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - dim-up
        sequence:
          - repeat:
              sequence:
                - device_id: 556982e3a4699eee4db65c98b6d24ab2
                  domain: light
                  entity_id: 26d11a34ca9b04a2f47165c6686929eb
                  type: brightness_increase
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 500
              while:
                - condition: trigger
                  id:
                    - dim-up
      - conditions:
          - condition: trigger
            id:
              - dim-down
        sequence:
          - repeat:
              sequence:
                - device_id: 556982e3a4699eee4db65c98b6d24ab2
                  domain: light
                  entity_id: 26d11a34ca9b04a2f47165c6686929eb
                  type: brightness_decrease
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 500
              while:
                - condition: trigger
                  id:
                    - dim-down
mode: restart
```
