### ISSUE TITLE
"No triggers have an ID set." working with triggers dosent work

### ISSUE THREAD

**Issue by worryboy** [Sian-Lee-SA/Home-Assistant-Switch-Manager#291]
i try to work with triggers as in normal automatisations but the defined trigger id isnt recognized. 

```
- wait_for_trigger:
    - platform: state
      entity_id:
        - sensor.wohnzimmer_switch_tab_action
      to: "off"
      id: to_off
  timeout:
    hours: 0
    minutes: 0
    seconds: 20
    milliseconds: 0
- if:
    - condition: trigger
      id: ""
  then: []
```

<img width="979" alt="2024-11-22_07-52-39" src="https://github.com/user-attachments/assets/5ae3dbb4-0446-4ea4-aca7-26c9d4a2d75c">

in t the if decission i cant work with the trigger id "to_off" .

Please assist
