### ISSUE TITLE
[Help] How do I expose variables to actions from blueprint?

### ISSUE THREAD

**Issue by TheUnlimited64** [Sian-Lee-SA/Home-Assistant-Switch-Manager#295]
I want to supply this repository with an improved blueprint for a smart knob, but I'm not very sure how I can expose a variable to an action like a normal HA blueprint. 

Can anyone give me an example?

I want to expose some home assistant state to the automation.

Example from my blueprint:

```yaml
- choose:
    # Handle rotation action
    - conditions:
        - condition: trigger
          id: rotation
        - condition: template
          value_template: >
            {{ not is_state(trigger.entity_id, 'unavailable') and
               not is_state(trigger.entity_id, 'unknown') and
               trigger.to_state.state not in ['unavailable', 'unknown'] }}
      sequence:
        - variables:
            delta_value: "{{ trigger.to_state.state | float(0) / 12.5 }}"
        - alias: "Execute rotation action"
          sequence: !input rotation_action
```
The delta_value variable is exposed to any action of mine.
