### ISSUE TITLE
Set identifier key from mqtt payload value.

### ISSUE THREAD

**Issue by nelferr** [Sian-Lee-SA/Home-Assistant-Switch-Manager#304]
First thanks for creating Switch Manager, really useful tool!
 
I´m trying to configure OXRS wall switches https://oxrs.io/docs/firmware/state-monitor-esp32.html with Switch Manager. These switches are mqtt based and use the following topic and payload.
 
An EVENT is reported to a topic of the form:
 
stat/CLIENTID
 
{
  "port": 1,
  "channel": 4,
  "index": 4,
  "type": "button",
  "event": "triple"
}
 
In OXRS each wall switch is hardwired to 1 of 32 ports. Each port can have to 1 to 4 channels (buttons) and the event can be single, double, etc..
 
 
Is there a way I can get Switch Manager to use the mqtt port value in the payload as an "identifier_key"? That would allow me to use 1 switch blueprint in Switch Manager vs 32.

Thanks 
Nelson

**Comment by Sian-Lee-SA** [comment]
FIrstly, it sounds like a really bad design to not distinguish a device by topic id. identifier_id is only relevent for event based (I'm going from memory, you can try using port as the identifier_key but I'm pretty sure it won't work). Either find some event that you can parse instead or you can hook an automation and just relay back to MQTT in whatever way you wish. Alternatively, contact the devs for the service providing the MQTT data ans tell them the format currently used is bad practice.

**Comment by nelferr** [comment]
Hi Sian,

Thanks for getting back to me.
The documentation does mention that identifier_id is only applicable for non mqtt devices. I tried it but the switch profile does not load with that setting in place.
The devs for OXRS do distinguish between OXRS devices but one device hosts up to 32, 4 button, mqtt driven, RJ45 connected, wall switches. In reality it is a switch with 32*4 buttons!

How could I can parse the event  \stat\OXRS “port” payload value, to use that as the identifier_id? Port event is what differentiates between the 32 connected switches.

Mqtt event:
\stat\<OXRS controller name>

{
  "port": 1,
  "channel": 4,
  "index": 4,
  "type": "button",
  "event": "triple"
}

Would it be using mqtt_sub_topics? I didn’t find any reference as to how to use this option in the examples you provide or existing blueprints.

My coding skills are very limited (to say the least 😊) but I have the impression I am close to find a working configuration to relay back to the OXRS community.

Thanks again,
Nelson

**Comment by Sian-Lee-SA** [comment]
an automation like the following will put the port as a topic stat/CLIENTID/{port]. Youn can then set the mqtt topic as stat/CLIENTID/+ and autodiscovery will also work, the same MQTT data will also be in that topic

```yaml
description: ""
triggers:
  - trigger: mqtt
    topic: stat/CLIENTID
conditions: []
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: 0
      retain: false
      topic: stat/CLIENTID/{{ trigger.payload_json.port }}
      payload: "{{ trigger.payload }}"
mode: single
```
