### ISSUE TITLE
Cannot select my blueprint

### ISSUE THREAD

**Issue by CoolID2** [Sian-Lee-SA/Home-Assistant-Switch-Manager#306]
Hi guys,

I have created my own blueprint under `/homeassistant/config/blueprints/switch_manager/`. 
2 New Files (copies of existing Files):
> zigbee2mqtt-ers-10tzbvk-aa-command.png
> zigbee2mqtt-ers-10tzbvk-aa-command.yaml

Restarted Homeassistant and also done the action "switch_manager.reload"

The blueprint does not appear in the listing of Switch-Manager 2.0.3 to add a new switch.

What am I doing wrong?

```
# COMMAND Mode triggering
# https://www.zigbee2mqtt.io/devices/ERS-10TZBVK-AA.html

name: ERS-10TZBVK-AA TS004F - COMMAND setting
service: Zigbee2MQTT
event_type: mqtt
mqtt_topic_format: zigbee2mqtt/+/action
buttons:
  - actions:
      - title: Press
        conditions:
          - key: payload
            value: toggle
      - title: Hold > 3s
        conditions:
          - key: payload
            value: hue_move
       - title: release
        conditions:
          - key: payload
            value: hue_stop           
      - title: Rotate right
        conditions:
          - key: payload
            value: brightness_step_up
      - title: Rotate left
        conditions:
          - key: payload
            value: brightness_step_down
      - title: Push+Hold and Rotate Left
        conditions:
          - key: payload
            value: color_temperature_step_down
      - title: Push+Hold and Rotate Right
        conditions:
          - key: payload
            value: color_temperature_step_up
```
