### ISSUE TITLE
ZHA / Philips Hue Tap Dial - no AutoDiscover and detection of button press

### ISSUE THREAD

**Issue by DerGehrmann** [Sian-Lee-SA/Home-Assistant-Switch-Manager#309]
I try to get the Philips Hue Tap Dial over ZHA running but I've got some issues with that.
I took the already existing blueprint for zigbee2mqtt to modify it and looked for other blueprints like Philips Hue Smart Button or similar.
 
First of all, I looked for the events this button gives me over zha_event:

```
event_type: zha_event
data:
  device_ieee: 00:17:88:01:0d:35:32:0f
  unique_id: 00:17:88:01:0d:35:32:0f:1:0xfc00
  device_id: dc5cf880c14b93a6b5b353e6f985aff4
  endpoint_id: 1
  cluster_id: 64512
  command: button_1_short_release
  args:
    button: button_1
    press_type: short_release
    command_id: 0
    duration: 1
    args:
      - 1
      - 3145728
      - 2
      - 33
      - 1
  params: {}
origin: LOCAL
time_fired: "2025-01-02T12:47:46.834406+00:00"
context:
  id: 01JGKGXH4J2MEB46CRS0145WFJ
  parent_id: null
  user_id: null
```

The not yet finished modification of the blueprint for ZHA looks like this:

```
name: Philips Hue Tap Dial
service: ZHA
event_type: zha_event
identifier_key: device_id
buttons:
  - d: M 197.73633 25.056641 C 102.18018 25.056637 24.716794 102.52002 24.716797 198.07617 L 197.73633 198.07617 L 197.73633 25.056641 z
    actions:
      - title: press
        conditions:
          - key: payload
            value: button_1_short_release
      - title: 2x press
        conditions:
          - key: payload
            value: button_1_double_press
      - title: 3x press
        conditions:
          - key: payload
            value: button_1_triple_press
      - title: 4x press
        conditions:
          - key: payload
            value: button_1_quadruple_press
      - title: 5x press
        conditions:
          - key: payload
            value: button_1_quintuple_press
      - title: hold / 0,8s
        conditions:
          - key: payload
            value: button_1_hold
      - title: hold (released)
        conditions:
          - key: payload
            value: button_1_long_release
  - d: M 197.73633 25.056641 L 197.73633 198.07617 L 370.75586 198.07617 C 370.75586 102.52002 293.29248 25.056641 197.73633 25.056641 z
    actions:
      - title: press
        conditions:
          - key: payload
            value: button_2_short_release
      - title: 2x press
        conditions:
          - key: payload
            value: button_2_double_press
      - title: 3x press
        conditions:
          - key: payload
            value: button_2_triple_press
      - title: 4x press
        conditions:
          - key: payload
            value: button_2_quadruple_press
      - title: 5x press
        conditions:
          - key: payload
            value: button_2_quintuple_press
      - title: hold / 0,8s
        conditions:
          - key: payload
            value: button_2_hold
      - title: hold (released)
        conditions:
          - key: payload
            value: button_2_long_release
  - d: M 24.716797 198.07617 C 24.716797 293.63232 102.18018 371.0957 197.73633 371.0957 L 197.73633 198.07617 L 24.716797 198.07617 z
    actions:
      - title: press
        conditions:
          - key: payload
            value: button_3_short_release
      - title: 2x press
        conditions:
          - key: payload
            value: button_3_double_press
      - title: 3x press
        conditions:
          - key: payload
            value: button_3_triple_press
      - title: 4x press
        conditions:
          - key: payload
            value: button_3_quadruple_press
      - title: 5x press
        conditions:
          - key: payload
            value: button_3_quintuple_press
      - title: hold / 0,8s
        conditions:
          - key: payload
            value: button_3_hold
      - title: hold (released)
        conditions:
          - key: payload
            value: button_3_long_release
  - d: M 197.73633 198.07617 L 197.73633 371.0957 C 293.29248 371.0957 370.75586 293.63232 370.75586 198.07617 L 197.73633 198.07617 z
    actions:
      - title: press
        conditions:
          - key: payload
            value: button_4_short_release
      - title: 2x press
        conditions:
          - key: payload
            value: button_4_double_press
      - title: 3x press
        conditions:
          - key: payload
            value: button_4_triple_press
      - title: 4x press
        conditions:
          - key: payload
            value: button_4_quadruple_press
      - title: 5x press
        conditions:
          - key: payload
            value: button_4_quintuple_press
      - title: hold / 0,8s
        conditions:
          - key: payload
            value: button_4_hold
      - title: hold (released)
        conditions:
          - key: payload
            value: button_4_long_release
```

With that it is possible to add one of these switches to the switch manager but the auto discover function is not working.
If I add the 'device_id' manually, it is possible to see the 'incoming' events via debugging, but the defined actions are not triggered and there is no green flash on the button and the text.

Incoming event over browser debugging:
```
{
    "data": {
        "device_ieee": "00:17:88:01:0d:35:32:0f",
        "unique_id": "00:17:88:01:0d:35:32:0f:1:0xfc00",
        "device_id": "dc5cf880c14b93a6b5b353e6f985aff4",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "button_1_short_release",
        "args": {
            "button": "button_1",
            "press_type": "short_release",
            "command_id": 0,
            "duration": 1,
            "args": [
                1,
                3145728,
                2,
                33,
                1
            ]
        },
        "params": {},
        "variables": null,
        "switch_id": "7",
        "button_last_state": [
            null,
            null,
            null,
            null
        ],
        "timestamp": 1735823167.315956
    },
    "event": "incoming"
}
```

What am I doing wrong or is there a hidden bug?

It would be great if somebody can head me in the right direction
