### ISSUE TITLE
About to add support for Button+, but I have questions

### ISSUE THREAD

**Issue by choenig** [Sian-Lee-SA/Home-Assistant-Switch-Manager#310]
Hi,

I'm in the process of adding support for http://button.plus devices.

The integration is based on mqtt, events are json formatted in the following subjects:

`buttonplus/buttonplus_1234567789/button/1-1/pushbutton`

`buttonplus_1234567789` represents the device id and `1-1` represents the button number (`1-1 ` up to `8-1`).

My current config looks like:

```
name: Button+ 3x
service: ButtonPlus
event_type: mqtt
mqtt_topic_format: buttonplus/+/button/+/pushbutton
mqtt_sub_topics: false
buttons:
  - x: 0
    y: 177
    width: 188
    height: 63
    conditions: "{{ data.topic.split('/')[-2] == '1-1' }}"
    actions:
      - title: click
        conditions:
          - key: event_type
            value: click
[...]
```

When using autodiscovery, the whole topic is detected, like `buttonplus/buttonplus_1234567789/button/1-1/pushbutton`.

While the replacement of the first `+` in my `mqtt_topic_format` is perfectly fine, the second one (which denotes the button number) should be kept as a`+`.

I also tried to use something like

```
mqtt_topic_format: buttonplus/+/button
mqtt_sub_topics: true
```

with the same result.

Is there any chance to make autodiscover only detect the prefix of the subject? Otherwise the use would need to manually replace the detected `1-1` with a `+` again or even remove the last two parts of the subject.

Thanks for your help and your great project!

br
/christian
