### ISSUE TITLE
Integration of ESPHome switches

### ISSUE THREAD

**Issue by marek-vrana** [Sian-Lee-SA/Home-Assistant-Switch-Manager#355]
Hi, I like switch manager a lot - already migrated all my zigbee switches to it. It works flawlessly, so I thought I'll try to migrate the rest (wifi). I (and probably many more users) have plenty of switches in esphome. Using [homeassistant.event](https://esphome.io/components/api#homeassistant-event-action) is very efficient and in case **I want to avoid migrating to mqtt** (SPOF), I realized it's not that simple.

My devices mostly use **press / press 2x / hold** and each of these types sends out a different `event_type`. I assume filtering `data:` is a part of a `buttons/actions/conditions` and that is already supported. 
Received event in HA looks like this:
```
event_type: esphome.switch_press
data:
  device_id: ***
  device: my-switch
  button: left
time_fired: ***
```
Template I ended up with:
```
name: My ESPHome switch
service: homeassistant
event_type: esphome.switch_click
identifier_key: device
buttons:
  actions:
    - title: press
      conditions:
        - key: type
          value: press
        - key: button
          value: left
```
This approach above requires building a separate template for `press 2x` and `hold`, does not make that much sense to me. Also firing a device specific event would require building a template for each switch with current implementation.

💡I was thinking about similar support as for mqtt - defining a custom `event_type` with additional property to define a selector for the topic (in this case for event) with support for identification of the device as this needs to be passed from switch-specific configuration:
```
event_type: esphome
esphome_event_selector: switch_(click|double|hold) # <-- or simply a list of events
identifier_key: device
```
The goal is to listen to all listed events, where `data.device` matches the one for switch and then narrowing down selection further via `buttons/actions/conditions`.

Do you think something like this is possible?

**Comment by Sian-Lee-SA** [comment]
I've never heard of esphome.switch_press as an event for ESPHome and generally data for switched through the event bus is contained with the same event type and identifier for each action. Only the data should be different. You can proxy https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/304 the input to format the incoming data to be more easier to manager through automations/Node-red or because you're using ESPHome, there should be options to fire your own specific event and data within the action through yaml. Either way you have options.

**Comment by Sian-Lee-SA** [comment]
```yaml
  - homeassistant.event:
      event: esphome.button_pressed
      data:
        device_id: ***
        device: my-switch
        button: left
        type:  press
  - homeassistant.event:
      event: esphome.button_pressed
      data:
        device_id: ***
        device: my-switch
        button: left
        type: hold
```
The above example for your esphome would be all you need to distinguish what button and action with same identifiers and event
