### ISSUE TITLE
Button highlight doesn't appear when swith has only one button

### ISSUE THREAD

**Issue by Mr-Groch** [Sian-Lee-SA/Home-Assistant-Switch-Manager#43]
I've noticed that if swith has only one button, then it won't be higlighted in editor view, even when I've defined in yaml button position. I think that highlighting should appear for all definied buttons - it helps to check in editor if button is working

**Comment by Sian-Lee-SA** [comment]
Thats because there's no svg shapes for single button switches

**Comment by Sian-Lee-SA** [comment]
Once a discovery works, it's generally safe to assume all actions and buttons will work as the blueprint has already been tested by the author

**Comment by Mr-Groch** [comment]
I've added new blueprint for single button switch with:

```
buttons:
  - x: 250
    y: 250
    width: 180
    shape: circle
    actions:
      - title: press
        conditions:
          - key: payload
            value: single
      - title: press 2x
        conditions:
          - key: payload
            value: double
      - title: hold
        conditions:
          - key: payload
            value: long
```

And it doesn't showed highlight area.
There also is existing blueprint (deconz-aqara-wireless-mini-switch) that also has button circle defined and it also doesn't show
