### ISSUE TITLE
Need Help working on ZHA Tradfri Remote

### ISSUE THREAD

**Issue by LennardPlay** [Sian-Lee-SA/Home-Assistant-Switch-Manager#62]
I got it working a little bit, but I'm not able to use "args" or "params" as conditions. Can someone help me with this problem?

Sadly ZHA only seperates the left and right button by these parameters:

Left Press:
```
event_type: zha_event
data:
  device_ieee: XXXXXXXXXXXXXXX
  unique_id: XXXXXXXXXXXXXXX
  device_id: XXXXXXXXXXXXXXX
  endpoint_id: 1
  cluster_id: 5
  command: press
  args:
    - 257
    - 13
    - 0
  params:
    param1: 257
    param2: 13
    param3: 0
origin: LOCAL
time_fired: "2023-01-07T08:58:36.536641+00:00"
context:
  id: XXXXXXXXXXXXXXX
  parent_id: null
  user_id: null
```

Right Press:
```
event_type: zha_event
data:
  device_ieee: XXXXXXXXXXXXXXX
  unique_id: XXXXXXXXXXXXXXX
  device_id: XXXXXXXXXXXXXXX
  endpoint_id: 1
  cluster_id: 5
  command: press
  args:
    - 256
    - 13
    - 0
  params:
    param1: 256
    param2: 13
    param3: 0
origin: LOCAL
time_fired: "2023-01-07T08:58:37.675986+00:00"
context:
  id: XXXXXXXXXXXXXXX
  parent_id: null
  user_id: null
```
Can someone help me with the right way to write these conditions? It's probably just a formatting issue.

**Comment by Sian-Lee-SA** [comment]
Could you try the lastest version and give template conditions a go? [template conditions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#template)

**Comment by Sian-Lee-SA** [comment]
I'm also just curious as to how ZHA handles switches etc. Is that really how the data comes in for all devices? there doesn't seem to be a friendly way to determine the button or action, do you literally have to interporate the args and params like you showed to determine what button or action was pushed?

**Comment by LennardPlay** [comment]
Your Idea about reaching out to the ZHA folks is great, but I don't think changing this is a possibility, because it would break all of the existing automations and HA blueprints.
As far as I know only this remote has this problem, and only the left and right button share the same command. The button release command is the same for all the buttons, only seperated by the args/params.

**Comment by Sian-Lee-SA** [comment]
I understand that but there's also the possiblity that they'll change it in a future update to be more towards the norm and how other devices data is sent... Eitherway the next update you can access those properties from the key, value conditions using dot notation like you were originally doing

**Comment by LennardPlay** [comment]
I've tried template condition, but hadn't had any luck. Could you please look over this code?
`#left
  - d: "m 54.065279,125.9253 a 226.71716,226.71716 0 0 0 -36.948383,123.9048 226.71716,226.71716 0 0 0 37.042197,123.841 l 66.872437,-44.9577 a 145.95894,145.95894 0 0 1 -23.15251,-78.8846 145.95894,145.95894 0 0 1 23.2763,-78.8011 z"
    shape: path
    actions:
      - title: press
        conditions: "{{ data.args == [257, 13, 0] }}"
`

**Comment by LennardPlay** [comment]
`  - d: "m 54.065279,125.9253 a 226.71716,226.71716 0 0 0 -36.948383,123.9048 226.71716,226.71716 0 0 0 37.042197,123.841 l 66.872437,-44.9577 a 145.95894,145.95894 0 0 1 -23.15251,-78.8846 145.95894,145.95894 0 0 1 23.2763,-78.8011 z"
    shape: path
    actions:
      - title: press
        conditions: "{{ data.args == [257, 13, 0] }}"`

**Comment by LennardPlay** [comment]
`
  - d: "m 54.065279,125.9253 a 226.71716,226.71716 0 0 0 -36.948383,123.9048 226.71716,226.71716 0 0 0 37.042197,123.841 l 66.872437,-44.9577 a 145.95894,145.95894 0 0 1 -23.15251,-78.8846 145.95894,145.95894 0 0 1 23.2763,-78.8011 z"
    shape: path
    actions:
      - title: press
        conditions: "{{ data.args == [257, 13, 0] }}"
`

**Comment by Sian-Lee-SA** [comment]
You would do `data.args[0] == 257 and data.args[1] == 13 and data.args[2] == 0` as I'm not sure jinja or even python will determine two different lists being the same if they're not the same reference

**Comment by Sian-Lee-SA** [comment]
I also haven't done extensive testing on the templated conditions but the simple test I did worked, so if that code I sent doesn't work then might be an issue with Switch Manager

**Comment by LennardPlay** [comment]
Sadly didn't work for me :/
`  - d: "m 54.065279,125.9253 a 226.71716,226.71716 0 0 0 -36.948383,123.9048 226.71716,226.71716 0 0 0 37.042197,123.841 l 66.872437,-44.9577 a 145.95894,145.95894 0 0 1 -23.15251,-78.8846 145.95894,145.95894 0 0 1 23.2763,-78.8011 z"
    shape: path
    actions:
      - title: press
        conditions: "{{ data.args[0] == 257 and data.args[1] == 13 and data.args[2] == 0 }}"`

**Comment by Sian-Lee-SA** [comment]
WIth the latest version you can also do

```yaml
conditions:
  - key: args.0
    value: 256
  - key: args.1
    value: 13
  - key: args.2
    value: 0
```

or

```yaml
conditions:
  - key: params.param1
    value: 256
  - key: params.param2
    value: 13
  - key: params.param3
    value: 0
```
