### ISSUE TITLE
REQUEST: Tasmota support

### ISSUE THREAD

**Issue by mihalski** [Sian-Lee-SA/Home-Assistant-Switch-Manager#70]
I have a lot of switches like the Zemismart KS-811 3 Gang Switch which work via Tasmota (which in turn works through MQTT).
Are there any plans on adding Tasmota support?

**Comment by Sian-Lee-SA** [comment]
Feel free to make blueprints for it then you can share those on here

**Comment by mihalski** [comment]
I'm sure the buttons are not right yet, but I thought it would at least pick up a button press to identify the device when listening for `stat/+/RESULT`. Is there some place that I could get help figuring this out?

```yaml
name: Zemismart KS-811 3 Gang Switch
service: Tasmota
event_type: mqtt
mqtt_topic_format: stat/+/RESULT
buttons:
  - actions:
      - title: press
        conditions:
          - key: payload
            value: SINGLE
      - title: press 2x
        conditions:
          - key: payload
            value: DOUBLE
      - title: press 3x
        conditions:
          - key: payload
            value: TRIPLE
      - title: press 4x
        conditions:
          - key: payload
            value: QUAD
      - title: press 5x
        conditions:
          - key: payload
            value: PENTA
      - title: hold
        conditions:
          - key: payload
            value: HOLD
```

**Comment by Sian-Lee-SA** [comment]
What is the full topic path for a device? (as shown in MQTT Explorer)

**Comment by Sian-Lee-SA** [comment]
Thats json encode, you'll need to access via the keys and not `key: payload`

**Comment by mihalski** [comment]
> eg `key: Button1.Action`

Thank you!

Now that I'm making some sort of progress, are there any plans to add a `Reload` feature to the integration? This has been by far the biggest hurdle to iterating towards a working templates.

Next I'll have to figure out how to submit templates.

**Comment by Sian-Lee-SA** [comment]
There already is a reload feature??

**Comment by mihalski** [comment]
> There already is a reload feature?? [Blueprints](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#blueprints)

Do you mean it can reload the switch templates?

**Comment by Sian-Lee-SA** [comment]
It reloads everything

**Comment by mihalski** [comment]
This seems to work now. Have I correctly laid everything out? I've named the file `tasmota-zemismart-ks811-3-gang-switch.yaml` and there is a corresponding png.

```yaml
name: Zemismart KS-811 3 Gang Switch
service: Tasmota
event_type: mqtt
mqtt_topic_format: stat/+/RESULT
buttons:
  - x: 100
    y: 123
    width: 120
    height: 92
    actions:
      - title: press
        conditions:
          - key: Button1.Action
            value: SINGLE
      - title: press 2x
        conditions:
          - key: Button1.Action
            value: DOUBLE
      - title: press 3x
        conditions:
          - key: Button1.Action
            value: TRIPLE
      - title: press 4x
        conditions:
          - key: Button1.Action
            value: QUAD
      - title: press 5x
        conditions:
          - key: Button1.Action
            value: PENTA
      - title: hold
        conditions:
          - key: Button1.Action
            value: HOLD
  - x: 100
    y: 219
    width: 120
    height: 92
    actions:
      - title: press
        conditions:
          - key: Button2.Action
            value: SINGLE
      - title: press 2x
        conditions:
          - key: Button2.Action
            value: DOUBLE
      - title: press 3x
        conditions:
          - key: Button2.Action
            value: TRIPLE
      - title: press 4x
        conditions:
          - key: Button2.Action
            value: QUAD
      - title: press 5x
        conditions:
          - key: Button2.Action
            value: PENTA
      - title: hold
        conditions:
          - key: Button2.Action
            value: HOLD
  - x: 100
    y: 314
    width: 120
    height: 92
    actions:
      - title: press
        conditions:
          - key: Button3.Action
            value: SINGLE
      - title: press 2x
        conditions:
          - key: Button3.Action
            value: DOUBLE
      - title: press 3x
        conditions:
          - key: Button3.Action
            value: TRIPLE
      - title: press 4x
        conditions:
          - key: Button3.Action
            value: QUAD
      - title: press 5x
        conditions:
          - key: Button3.Action
            value: PENTA
      - title: hold
        conditions:
          - key: Button3.Action
            value: HOLD
```
