### ISSUE TITLE
how to create Zigbee2MQTT WXKG02LM_rev2 Aqara wall 2 gang?

### ISSUE THREAD

**Issue by platini76** [Sian-Lee-SA/Home-Assistant-Switch-Manager#75]
hello, please someone can explain me how to create this switch in blueprints?
thanks
plat

**Comment by Sian-Lee-SA** [comment]
Just follow the [Blueprint section](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#blueprints)

**Comment by Sian-Lee-SA** [comment]
You can also just use the WXKG07LM blueprint already in the Zigbee2MQTT as they're pretty much the same

**Comment by platini76** [comment]
I used it... and cut some functions that are not in 02 model.

```
name: Aqara 2 Gang Remote (WXKG02LM)
service: Zigbee2MQTT
event_type: mqtt
mqtt_topic_format: zigbee2mqtt/+/action
buttons:
  - actions:
      - title: press
        conditions:
          - key: payload
            value: single
      - title: press 2x
        conditions:
          - key: payload
            value: double
      - title: hold
        conditions:
          - key: payload
            value: hold
      - title: hold (released)
        conditions:
          - key: payload
            value: release
```


but when I go to autodiscover it won't work..
