### ISSUE TITLE
KNX support?

### ISSUE THREAD

**Issue by pissten** [Sian-Lee-SA/Home-Assistant-Switch-Manager#88]
Hi,

Thanks you for sharing this awesome addon!
Would love to see knx support also ;) Would that be possible?

Best regards
Chris

**Comment by Sian-Lee-SA** [comment]
I only make blueprints for the devices I own and the community has posted their own blueprints for theirs. Unless someone tasks on the task for your device and they have one to test on then you would have to wait till it's added to this repo from them. Alternatively you can copy a blueprint and adjust it to how your device works (may seem intimidating at first but is actually fairly straight forward, will probably do a YouTube video soon on making blueprints). Also I'm not familiar with KNX but generally all stateless services (assuming you're using a service different to what's already available) are sent through the Event Bus which Switch Manager reads and handles

**Comment by Sian-Lee-SA** [comment]
Just looking at the KNX integration and you can find the events on their page https://www.home-assistant.io/integrations/knx/. You can adapt those events to a blueprint. I would copy a blueprint that is similar to your switch and uses the event and not mqtt (so ZHA, deCONZ etc.)

**Comment by pissten** [comment]
![image](https://user-images.githubusercontent.com/16886605/214892494-f6b9a23c-6a62-4481-af2b-5e37f8cfb150.png)

**Comment by Sian-Lee-SA** [comment]
Based on those events you would set the identifier key to `destination` and conditions to the data.data.0 key.

```yaml
name: Universal Switch
service: KNX
event_type: knx_event
identifier_key: destination
conditions:
  - key: direction
    value: Incoming
buttons:
  - actions:
      - title: press
        conditions:
          - key: data.0
            value: 134
  - actions:
      - title: press
        conditions:
          - key: data.0
            value: 133
```

**Comment by pissten** [comment]
Thank you so much! I got it working by swapping condition list with template, using your code from above.

`name: Universal Switch
service: KNX
event_type: knx_event
identifier_key: destination
conditions:
  - key: direction
    value: Incoming
buttons:
  - x: 184
    y: 184
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ data.data[0] == 1 }}"
  - x: 530
    y: 184
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ data.data[0] == 0 }}"
  - x: 184
    y: 414
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ _data.destination == {{destination}} and_ data.data[0] == 1 }}"
  - x: 530
    y: 414
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ __data.destination == {{destination}}_ and_ data.data[0] == 0 }}"`

I'm also trying to figure out how to use variables to be able to pre-define what GroupAddresses are connected to each button. As you can see in the button (3) and (4) template condition. But I surely haven't understood that part though :D 

The problem with the KNX switches would probably be that the buttons are assigned dynamically GroupAddresses by the knx programmer, and will be different from switch to switch and project to project. So unike the switches used in your blueprint, that have hardcoded addresses or value_data, the knx blueprints should probably use the identifier_key for each buttons-> actions sequence? Would that be possible? any ideas would truly be appreciated!

best regards
Christian

**Comment by Sian-Lee-SA** [comment]
Reading your blueprint and the event's you posted above it doesn't connect. In the event you have data[0] as being 134 but in your conditions you're checking if it equals 1 or 0?

**Comment by pissten** [comment]
I'm sorry for not explaining fully. I adjusted the code some, for testing purposes. The Knx events i first presented for you, were based on a feedback channel for the actual brightness of the actuator channel. ( State is represented in 0-255 ) The one I used in the blueprint is a full surface push on the same button, which triggeres scenes ( 0 = evening lights / 1 = night lights ) As i mentioned in my previous post, the four individual buttons are connected to groupAddresses ( destination ) and those won't be consistent across Knx switches. Would be nice if it were possible to auto discover each button destination address. Now it seems that the indentification_id is only discovered once and is common for the entire switch?
________________________________

**Comment by Sian-Lee-SA** [comment]
Yes, every switch needs a set identifier that doesn't change, like I said in previous post, you might need to relay the events in an automation. The groupAdresses and how it correlates to the switch is not something I can rundown without actually having the device and testing myself so sorry about that.

**Comment by pissten** [comment]
Hi again :)

Sorry for bugging you.I hope it's okay if I aske another question. As you probably noticed already i'm pretty noob in the coding part, so please bare with me :D
Also technical terms in a foreign language, isn't making this any easer for me ;)

But, I've made some progress on the KNX switch, but I would really need a dynamic way to set with GroupAddress to expect for each button press.

I've used source as the identifier for my switch, which is a static id. All the buttons on the KNX switch is programmed to individual GroupAddresses, and I would like to define what GA (ex. '4/0/3') the buttons should expext on event bus, when pushing the physical button.

So far I've had luck setting the GA as a condition in the blueprint, but that wouldn't make this a very good blueprint for knx, as the GA's would change from switch to switch.

So I've tried to use your variables as a condition in the blueprint, and defined them through switch manager GUI. This Is were i'm stuck at the moment, and would really appreciate some help, If you wouldn't mind.

So this is working, but not plexiable enough:
```
name: Universal Switch
service: KNX
event_type: knx_event
identifier_key: source
conditions:
  - key: direction
    value: Incoming
buttons:
  - x: 184
    y: 184
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ data.data[0] == 1 }}"
  - x: 530
    y: 184
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ data.data[0] == 0 }}"
  - x: 184
    y: 414
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ data.destination == '4/0/4' }}"
  - x: 530
    y: 414
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ data.destination == '4/0/3' }}"
```

Would like to make this work, but unsure how to define the variables:

```
name: Universal Switch
service: KNX
event_type: knx_event
identifier_key: source
conditions:
  - key: direction
    value: Incoming
buttons:
  - x: 184
    y: 184
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ data.destination == {{data.variables.button_1_ga}} }}"
  - x: 530
    y: 184
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ data.destination == {{data.variables.button_2_ga}} }}"
  - x: 184
    y: 414
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ data.destination == {{data.variables.button_3_ga}} }}"
  - x: 530
    y: 414
    width: 115
    height: 230
    actions:
      - title: press
        conditions: "{{ data.destination == {{data.variables.button_4_ga}} }}"
```


![image](https://user-images.githubusercontent.com/16886605/215344435-158ec9d0-eac4-48e4-b00b-e17c647529df.png)
