### ISSUE TITLE
New ZHA remote

### ISSUE THREAD

**Issue by gorstj** [Sian-Lee-SA/Home-Assistant-Switch-Manager#92]
Hi, sorry to open an issue for this but I can't fathom GitHub yet.

I have imported the following Tuya 4 button remove from zigbee2mqtt to ZHA
I have only confirmed working for the 3 button, but assume it will also work with the 4th button.

I am using the png from the zigbee2mgtt integration

```
name: TuYa 4 Button Scene (SS5300ZB)
service: ZHA
event_type: zha_event
identifier_key: device_id
buttons:
  - x: 66
    y: 102
    width: 32
    conditions:
      - key: endpoint_id
        value: 1
    actions:
      - title: press
        conditions:
          - key: command
            value: remote_button_short_press
      - title: press 2x
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
  - x: 66
    y: 204
    width: 32
    conditions:
      - key: endpoint_id
        value: 2
    actions:
      - title: press
        conditions:
          - key: command
            value: remote_button_short_press
      - title: press 2x
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
  - x: 66
    y: 302
    width: 32
    actions:
    conditions:
      - key: endpoint_id
        value: 3
    actions:
      - title: press
        conditions:
          - key: command
            value: remote_button_short_press
      - title: press 2x
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
  - x: 66
    y: 405
    width: 32
    conditions:
      - key: endpoint_id
        value: 4
    actions:
      - title: press
        conditions:
          - key: command
            value: remote_button_short_press
      - title: press 2x
        conditions:
          - key: command
            value: remote_button_double_press
      - title: hold
        conditions:
          - key: command
            value: remote_button_long_press
```
