### ISSUE TITLE
Pull requests - new ZHA devices

### ISSUE THREAD

**Issue by gorstj** [Sian-Lee-SA/Home-Assistant-Switch-Manager#98]
Apologies, but I don't know how to use GitHub to facilitate a proper pull request.

Here are some ZHA devices I have created (used the images from the zigbee2mqtt versions)

Thank you for such a great plugin. Should be default within HA!

Only improvement would be a 'wizard' to create new switch types in the UI.

mycustom-zha-ikea-e1766.yaml
```
name: Ikea Open/Close Remote E1766
service: ZHA
event_type: zha_event
identifier_key: device_id
buttons:
  ## Those buttons only accept single tap actions
  - x: 182
    y: 90
    width: 65
    actions:
      - title: init
        conditions:
          - key: command
            value: up_open
      - title: hold (release)
        conditions:
          - key: command
            value: stop_opening
  - x: 182
    y: 280
    width: 65
    actions:
      - title: init
        conditions:
          - key: command
            value: down_close
      - title: hold (release)
        conditions:
          - key: command
            value: stop_closing
```

mycustom-zha-sonoff-snzb-01.yaml
```
name: Sonoff SNZB 01
service: ZHA
event_type: zha_event
identifier_key: device_id
buttons:
  - actions:
      - title: press
        conditions:
          - key: command
            value: toggle
      - title: press 2x
        conditions:
          - key: command
            value: "on"
      - title: hold
        conditions:
          - key: command
            value: "off"
```

mycustom-zha-xiaomi-smart-wireless-switch-wxkg01lm.yaml
```
name: Xiaomi Smart Wireless Switch (WXKG01LM)
service: ZHA
event_type: zha_event
identifier_key: device_id
buttons:
  - actions:
      - title: press
        conditions:
          - key: args.click_type
            value: single
      - title: press 2x
        conditions:
          - key: args.click_type
            value: double
      - title: press 3x
        conditions:
          - key: args.click_type
            value: triple
      - title: press 4x
        conditions:
          - key: args.click_type
            value: quadruple
      - title: press >4x
        conditions:
          - key: args.click_type
            value: furious
      - title: hold
        conditions:
          - key: command
            value: hold
      - title: hold (released)
        conditions:
          - key: command
            value: release
```
