### ISSUE TITLE
How to build automations to handle a hold -> hold (release) cycle?

### ISSUE THREAD

**Issue by bendikrb** [Sian-Lee-SA/Home-Assistant-Switch-Manager#99]
Hi,
first off; thanks for your awesome work putting together this project! 

Now, I'm struggling to understand how I should build my scripts in the case where I need a `hold (release)` action to interrupt the `hold` action sequence. It's possible I've completely overlooked it in the documentation or in the countless of google searches I've done, but all I've seen is how to write the generic parts of the blueprint YAML for one specific device;
I would love to see some more documentation or examples on how to (best) utilize switch manager beyond just getting button triggers.

I have written blueprints for a 3 of my switches which weren't available yet - so I get _that_ part at least.. =)

See below to get an idea on what I'm struggling with 😵‍💫  I've tried different variants of this - but I can't get the `wait_for_trigger` trigger to actually trigger!

Thanks in advance for any help!

```yaml
- repeat:
    until: "{{ wait.trigger is not none or repeat.index >= 100 }}"
    sequence:
      - service: system_log.write
        data:
          message: Pretending to turn up brightness ... {{ repeat.index }}
      - wait_for_trigger:
          - platform: event
            event_type: zha_event
            event_data:
              device_id: "{{ data.device_id }}"
              command: stop_with_on_off
        timeout:
          milliseconds: 200

```
![image](https://user-images.githubusercontent.com/152300/217400426-adffc7d6-82a8-4ed5-9993-85ce2583f5b6.png)

**Comment by bendikrb** [comment]
Oh! No, that one slipped pass me! That's what I get for never bothering to watch videos in docs...
I think I'll be good with the variable setting service!

My first idea was infact to use button_last_state or some other variables in data to achieve this, but as far as I could tell it wouldn't help much in that context .. 

The switch doesn't repeat the hold action, by the way. Furthermore, the `stop_with_on_off` command looks the same whether you initiated from the ON button or the OFF button - so to discern that, the button_last_state variable came in handy!

Dumping the config of the switch in question here, for reference. I'll put in a pr someday soon!

```yaml
name: Namron 4 button switch
service: ZHA
event_type: zha_event
identifier_key: device_id
buttons:
  # Top left (endpoint 1 "ON")
  - x: 118
    y: 115
    width: 165
    height: 279
    actions:
      - title: press
        conditions:
          - key: endpoint_id
            value: 1
          - key: cluster_id
            value: 6
          - key: command
            value: 'on'
      - title: hold
        conditions: >
          {{ data.endpoint_id == 1
          and data.cluster_id == 8
          and data.command == 'move_with_on_off'
          and data.params.move_mode == 0 }}
      - title: hold (released)
        conditions: >
          {{ data.endpoint_id == 1
          and data.cluster_id == 8
          and data.command == 'stop_with_on_off'
          and data.button_last_state[0].title == 'hold' }}
  # Bottom left (endpoint 2 "ON")
  - x: 118
    y: 398
    width: 165
    height: 279
    actions:
      - title: press
        conditions:
          - key: endpoint_id
            value: 2
          - key: cluster_id
            value: 6
          - key: command
            value: 'on'
      - title: hold
        conditions: >
          {{ data.endpoint_id == 2
          and data.cluster_id == 8
          and data.command == 'move_with_on_off'
          and data.params.move_mode == 0 }}
      - title: hold (released)
        conditions: >
          {{ data.endpoint_id == 2
          and data.cluster_id == 8
          and data.command == 'stop_with_on_off'
          and data.button_last_state[1].title == 'hold' }}

  # Top right (endpoint 1 "OFF")
  - x: 516
    y: 115
    width: 165
    height: 279
    actions:
      - title: press
        conditions:
          - key: endpoint_id
            value: 1
          - key: cluster_id
            value: 6
          - key: command
            value: 'off'
      - title: hold
        conditions: >
          {{ data.endpoint_id == 1
          and data.cluster_id == 8
          and data.command == 'move_with_on_off'
          and data.params.move_mode == 1 }}
      - title: hold (released)
        conditions: >
          {{ data.endpoint_id == 1
          and data.cluster_id == 8
          and data.command == 'stop_with_on_off'
          and data.button_last_state[2].title == 'hold' }}
  # Bottom right (endpoint 2 "OFF")
  - x: 516
    y: 398
    width: 165
    height: 279
    actions:
      - title: press
        conditions:
          - key: endpoint_id
            value: 2
          - key: cluster_id
            value: 6
          - key: command
            value: 'off'
      - title: hold
        conditions: >
          {{ data.endpoint_id == 2
          and data.cluster_id == 8
          and data.command == 'move_with_on_off'
          and data.params.move_mode == 1 }}
      - title: hold (released)
        conditions: >
          {{ data.endpoint_id == 2
          and data.cluster_id == 8
          and data.command == 'stop_with_on_off'
          and data.button_last_state[3].title == 'hold' }}
```
